packages:
  - "."

strictPeerDependencies: false

overrides:
  ini: 1.3.8
  lodash: 4.18.1
  tmp: 0.2.6

minimumReleaseAgeExclude:
  - '@commitlint/cli@21.0.2'
  - '@commitlint/is-ignored@21.0.2'
  - '@commitlint/lint@21.0.2'
  - '@commitlint/load@21.0.2'
  - '@commitlint/message@21.0.2'
  - '@commitlint/parse@21.0.2'
  - '@commitlint/read@21.0.2'
  - '@commitlint/rules@21.0.2'
  - '@commitlint/top-level@21.0.2'
